DELETE FROM ARTIFACT_AUTHZ WHERE ARTIFACT_AUTHZ_ID IN ('AI_OPS_DATA_DOCUMENT_RW_ALL', 'AI_OPS_DATA_READ_ALL', 'AI_OPS_ALL_USERS');
DELETE FROM ARTIFACT_GROUP_MEMBER WHERE ARTIFACT_GROUP_ID IN ('AI_OPS_DATA_DOCUMENT_RW', 'AI_OPS_DATA_READ', 'AI_OPS_SCREENS');
DELETE FROM ARTIFACT_GROUP WHERE ARTIFACT_GROUP_ID IN ('AI_OPS_DATA_DOCUMENT_RW', 'AI_OPS_DATA_READ', 'AI_OPS_SCREENS');

DELETE FROM USER_GROUP WHERE USER_GROUP_ID = 'AI_OPERATOR';
